"""File-based ledger system for tracking strategy events and attribution.

This module provides an append-only JSONL ledger that captures:
1. Strategy configuration changes and activations
2. Signals generated by each strategy
3. Orders placed and filled
4. Position updates and PnL attribution

Key features:
- Append-only JSONL format (one event per line)
- Deterministic state reconstruction from events
- Per-strategy attribution of orders, fills, and PnL
- Time-ordered event stream
"""

import json
import uuid
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any


@dataclass
class LedgerEvent:
    """Base class for all ledger events."""

    event_id: str  # UUID
    timestamp: str  # ISO 8601 timestamp
    event_type: str  # Type discriminator


@dataclass
class StrategyConfigActivatedEvent(LedgerEvent):
    """Event: Strategy configuration version was activated."""

    strategy_id: str
    version: int
    config_snapshot: dict[str, Any]  # Full config at activation time

    def __init__(self, strategy_id: str, version: int, config_snapshot: dict[str, Any]):
        self.event_id = str(uuid.uuid4())
        self.timestamp = datetime.now(UTC).isoformat()
        self.event_type = "strategy_config_activated"
        self.strategy_id = strategy_id
        self.version = version
        self.config_snapshot = config_snapshot


@dataclass
class SignalGeneratedEvent(LedgerEvent):
    """Event: Strategy generated a trading signal."""

    strategy_id: str
    version: int
    symbol: str
    signal_type: str  # 'buy', 'sell', 'hold'
    strength: float
    metadata: dict[str, Any]  # Additional signal data

    def __init__(
        self,
        strategy_id: str,
        version: int,
        symbol: str,
        signal_type: str,
        strength: float,
        metadata: dict[str, Any] | None = None,
    ):
        self.event_id = str(uuid.uuid4())
        self.timestamp = datetime.now(UTC).isoformat()
        self.event_type = "signal_generated"
        self.strategy_id = strategy_id
        self.version = version
        self.symbol = symbol
        self.signal_type = signal_type
        self.strength = strength
        self.metadata = metadata or {}


@dataclass
class OrderPlacedEvent(LedgerEvent):
    """Event: Order was placed with broker."""

    strategy_id: str
    version: int
    client_order_id: str
    symbol: str
    side: str
    quantity: str  # Decimal as string for JSON serialization
    order_type: str
    limit_price: str | None  # Decimal as string

    def __init__(
        self,
        strategy_id: str,
        version: int,
        client_order_id: str,
        symbol: str,
        side: str,
        quantity: Decimal,
        order_type: str,
        limit_price: Decimal | None = None,
    ):
        self.event_id = str(uuid.uuid4())
        self.timestamp = datetime.now(UTC).isoformat()
        self.event_type = "order_placed"
        self.strategy_id = strategy_id
        self.version = version
        self.client_order_id = client_order_id
        self.symbol = symbol
        self.side = side
        self.quantity = str(quantity)
        self.order_type = order_type
        self.limit_price = str(limit_price) if limit_price is not None else None


@dataclass
class OrderFilledEvent(LedgerEvent):
    """Event: Order was filled by broker."""

    strategy_id: str
    version: int
    client_order_id: str
    symbol: str
    side: str
    quantity: str  # Decimal as string
    fill_price: str  # Decimal as string
    fill_time: str  # ISO 8601 timestamp

    def __init__(
        self,
        strategy_id: str,
        version: int,
        client_order_id: str,
        symbol: str,
        side: str,
        quantity: Decimal,
        fill_price: Decimal,
        fill_time: datetime,
    ):
        self.event_id = str(uuid.uuid4())
        self.timestamp = datetime.now(UTC).isoformat()
        self.event_type = "order_filled"
        self.strategy_id = strategy_id
        self.version = version
        self.client_order_id = client_order_id
        self.symbol = symbol
        self.side = side
        self.quantity = str(quantity)
        self.fill_price = str(fill_price)
        self.fill_time = fill_time.isoformat()


@dataclass
class PositionUpdateEvent(LedgerEvent):
    """Event: Strategy position was updated."""

    strategy_id: str
    version: int
    symbol: str
    quantity: int
    avg_price: str  # Decimal as string
    current_price: str  # Decimal as string
    unrealized_pnl: str  # Decimal as string

    def __init__(
        self,
        strategy_id: str,
        version: int,
        symbol: str,
        quantity: int,
        avg_price: Decimal,
        current_price: Decimal,
        unrealized_pnl: Decimal,
    ):
        self.event_id = str(uuid.uuid4())
        self.timestamp = datetime.now(UTC).isoformat()
        self.event_type = "position_update"
        self.strategy_id = strategy_id
        self.version = version
        self.symbol = symbol
        self.quantity = quantity
        self.avg_price = str(avg_price)
        self.current_price = str(current_price)
        self.unrealized_pnl = str(unrealized_pnl)


class Ledger:
    """
    Append-only JSONL ledger for tracking strategy events.

    File format: out/ledger/YYYY-MM-DD.jsonl
    Each line is a JSON object representing one event.

    Responsibilities:
    1. Append events to current day's ledger file
    2. Read events from ledger files
    3. Rebuild state deterministically from event stream
    """

    def __init__(self, ledger_dir: Path | str = Path("out/ledger")):
        """
        Initialize ledger.

        Args:
            ledger_dir: Directory to store ledger files
        """
        self.ledger_dir = Path(ledger_dir)
        self.ledger_dir.mkdir(parents=True, exist_ok=True)

    def append(self, event: LedgerEvent) -> None:
        """
        Append event to today's ledger file.

        Args:
            event: Event to append
        """
        # Determine today's file
        today = datetime.now(UTC).date()
        ledger_file = self.ledger_dir / f"{today.isoformat()}.jsonl"

        # Convert event to dict
        event_dict = asdict(event)

        # Append to file (atomic write not needed for append-only)
        with open(ledger_file, "a") as f:
            f.write(json.dumps(event_dict) + "\n")

    def read_all(self, date: datetime.date | None = None) -> list[dict[str, Any]]:
        """
        Read all events from ledger.

        Args:
            date: Optional date to read specific day's events. If None, read all files.

        Returns:
            List of event dictionaries in chronological order
        """
        events = []

        if date:
            # Read specific date
            ledger_file = self.ledger_dir / f"{date.isoformat()}.jsonl"
            if ledger_file.exists():
                with open(ledger_file) as f:
                    for line in f:
                        events.append(json.loads(line))
        else:
            # Read all ledger files in chronological order
            ledger_files = sorted(self.ledger_dir.glob("*.jsonl"))
            for ledger_file in ledger_files:
                with open(ledger_file) as f:
                    for line in f:
                        events.append(json.loads(line))

        return events

    def rebuild_state(self) -> dict[str, Any]:
        """
        Deterministically rebuild state from ledger events.

        This function processes all events in order and reconstructs:
        - Active strategy configurations
        - Per-strategy positions
        - Per-strategy realized and unrealized PnL
        - Order history

        Returns:
            Dictionary containing rebuilt state:
            {
                "strategies": {
                    "strategy_id": {
                        "active_version": int,
                        "config": dict,
                        "positions": {
                            "symbol": {
                                "quantity": int,
                                "avg_price": Decimal,
                                "unrealized_pnl": Decimal
                            }
                        },
                        "realized_pnl": Decimal,
                        "orders": [
                            {
                                "client_order_id": str,
                                "symbol": str,
                                "side": str,
                                "quantity": Decimal,
                                "status": str,
                                "fill_price": Decimal | None
                            }
                        ]
                    }
                },
                "last_event_timestamp": str
            }
        """
        state: dict[str, Any] = {"strategies": {}, "last_event_timestamp": None}

        events = self.read_all()

        for event_dict in events:
            event_type = event_dict["event_type"]
            strategy_id = event_dict.get("strategy_id")

            # Initialize strategy state if needed
            if strategy_id and strategy_id not in state["strategies"]:
                state["strategies"][strategy_id] = {
                    "active_version": None,
                    "config": None,
                    "positions": {},
                    "realized_pnl": Decimal("0"),
                    "orders": [],
                }

            strategy_state = state["strategies"].get(strategy_id) if strategy_id else None

            # Process event based on type
            if event_type == "strategy_config_activated":
                if strategy_state:
                    strategy_state["active_version"] = event_dict["version"]
                    strategy_state["config"] = event_dict["config_snapshot"]

            elif event_type == "order_placed":
                if strategy_state:
                    strategy_state["orders"].append(
                        {
                            "client_order_id": event_dict["client_order_id"],
                            "symbol": event_dict["symbol"],
                            "side": event_dict["side"],
                            "quantity": Decimal(event_dict["quantity"]),
                            "order_type": event_dict["order_type"],
                            "limit_price": (
                                Decimal(event_dict["limit_price"])
                                if event_dict.get("limit_price")
                                else None
                            ),
                            "status": "placed",
                            "fill_price": None,
                        }
                    )

            elif event_type == "order_filled":
                if strategy_state:
                    # Find and update order status
                    client_order_id = event_dict["client_order_id"]
                    for order in strategy_state["orders"]:
                        if order["client_order_id"] == client_order_id:
                            order["status"] = "filled"
                            order["fill_price"] = Decimal(event_dict["fill_price"])

                            # Update realized PnL (simplified: just track total)
                            fill_value = Decimal(event_dict["quantity"]) * Decimal(
                                event_dict["fill_price"]
                            )
                            if event_dict["side"] == "sell":
                                strategy_state["realized_pnl"] += fill_value
                            else:
                                strategy_state["realized_pnl"] -= fill_value

                            break

            elif event_type == "position_update" and strategy_state:
                symbol = event_dict["symbol"]
                strategy_state["positions"][symbol] = {
                    "quantity": event_dict["quantity"],
                    "avg_price": Decimal(event_dict["avg_price"]),
                    "current_price": Decimal(event_dict["current_price"]),
                    "unrealized_pnl": Decimal(event_dict["unrealized_pnl"]),
                }

            # Track last event timestamp
            state["last_event_timestamp"] = event_dict["timestamp"]

        return state
